version: '3.8'

services:
  vottery-operating-backend:
    container_name: vottery-operating-backend
    image: vottery-operating-system:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn pm2-runtime start ./dist/main.js -i max
    ports:
      - 2323:3000
    env_file:
      - .env.prod
    volumes:
      - ./secrets:/usr/src/app/secrets
    restart: unless-stopped

