version: '3.8'

services:
  vottery-operating-backend:
    container_name: vottery-operating-backend
    image: vottery-operating-system:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 2324:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./secrets:/usr/src/app/secrets
    env_file:
      - .env.staging
    restart: unless-stopped

